### ISSUE TITLE
Can I use mosquitto_tls_set()?

### ISSUE THREAD

**Issue by eason112** [NinevaStudios/mqtt-utilities-unreal#31]
I want to connect AWS iot ,but when i use mosquitto_tls_set(mosq, cafilePath, NULL, certPath, keyPath, NULL);or connection.tls_set(cafilePath, NULL, certPath, keyPath, NULL); it return MOSQ_ERR_NOT_SUPPORTED

**Comment by tustanivsky** [comment]
> I want to connect AWS iot ,but when i use mosquitto_tls_set(mosq, cafilePath, NULL, certPath, keyPath, NULL);or connection.tls_set(cafilePath, NULL, certPath, keyPath, NULL); it return MOSQ_ERR_NOT_SUPPORTED

There is a `tls_support` branch in this repo which might be helpful. It's quite an old one though so not sure if it's still working

**Comment by ennorehling** [comment]
The mention of the tls_support branch here was a really helpful pointer. It contains a newer version of the windows mosquitto library, linked against the correct runtime (see issue #40), and some refactorings, like joining the Utils directories.

Sadly, it seems to have dropped Linux support :-(

For our project, we rebased it on master and plan to eventually backfill the Linux support if it turns out that we need it.

**Comment by eason112** [comment]
OK, thanks!
