### ISSUE TITLE
Is it possible to add support of HTML5 platform?

### ISSUE THREAD

**Issue by YevYar** [NinevaStudios/mqtt-utilities-unreal#8]
Hello! Thank you for your plugin!
I have a project on UE version 4.22. I need to package the project for HTML5 platform. In My project I need MQTT-client.
Tell me please, is it possible to add support of HTML5 platform? If yes, please, give me a peace of advise, how to do it.

Thank you in advance!

**Comment by tustanivsky** [comment]
Hey! Unfortunately, we won't be able to assist you with this issue since our team doesn't have any experience in developing UE projects targeted for this particular platform. However, you can begin with some research on how MQTT client can be embedded into an HTML5 application at all. You can check out Paho JavaScript library (https://www.eclipse.org/paho/index.php?page=clients/js/index.php) which might be a good option here. Also, you'll have to find a way how to build some kind of wrapper for it in order to communicate with MQQT broker from within your app.

**Comment by YevYar** [comment]
Okay, thank you for your ideas. I'll describe solution for my project, probably, it can help somebody.
I've considered my requirements to the client and have found, that my system must just publish messages in topics and receive messages on these topics (I don't need to create different subscriptions). So, I've decided to use simple WebSockets ([there is a plugin for UE 4.22](https://github.com/kristjanvalur/UEWebsocket)). Subscriptions I handle on my NodeJS server.
On NodeJS server I have MQTT broker and client. This client represents my UE project to the broker. My game send message by socket to the socket on my server, a handler of socket events send commands to the MQTT-client and client sends MQTT messages to the broker. I've attached listeners on client events. Therefore, when client receive message from broker, I handle them and send them by socket to the game.
I create subscriptions by sending a command to the client, when socket receive first message from my game.
